### PR TITLE
make transport optional

### PR DESCRIPTION
**Pull request by ronenhamias**

### CODE REVIEW

**Comment by ronenhamias** [comment]
NoTransportExtension. means LocalTransport?

**Comment by segabriel** [comment]
> NoTransportExtension. means LocalTransport?

Unfortunately yeap, it seems convoluted a bit, but I needed to have some gateway tests without specifying transport and discovery implementations, so I just copy-paste existing tests and changed their extension.

**Review by artem-v — DISMISSED** [review]
Proposed changes in names:
In the new types:
`NO_ADDRESS -> NULL_ADDRESS`
`NO_DISCOVERY-> NO_OP_DISCOVERY`
In the test names and extension classes:
`...NoTransport... -> ...Local...`

**Comment by artem-v** [comment]
After re-shaking heads a little bit, new desired changes are as following: 

In Microservices  start()  :
```java
    return transportBootstrap
        .start(methodRegistry)
        .publishOn(scheduler)
        .flatMap(
            input -> {
              ServiceCall call;
              Address serviceAddress;
              Executor workerPool;

              if (input != ServiceTransportBootstrap.noOpInstance) {
                ClientTransport clientTransport = input.clientTransport;
                serviceAddress = input.address;
                workerPool = input.resources.workerPool().orElse(null);
                call = new ServiceCall(clientTransport, serviceRegistry, methodRegistry);
              } else {
                call = new ServiceCall(null, null, methodRegistry);
                serviceAddress = null;
                workerPool = null;
              }

```

In ServiceTransportBootstrap:
```java
  public static class ServiceTransportBootstrap {

    public static final ServiceTransportBootstrap noOpInstance = new ServiceTransportBootstrap();

    private String host;
    private int port = 0;
    private Supplier<TransportResources> resourcesSupplier = () -> null;

    ...

    private Mono<ServiceTransportBootstrap> start(ServiceMethodRegistry methodRegistry) {
      return Mono.fromSupplier(resourcesSupplier)
          .flatMap(TransportResources::start)
          .map(
              resources -> {
                  ...
              })
          .doOnError(ex -> LOGGER.error("Failed to start service transport resources: " + ex))
          .flatMap(
              resources -> {
                             ...
              })
          .map(
              serverTransport -> {
                ...
                return this;
              })
          .switchIfEmpty(Mono.just(ServiceTransportBootstrap.noOpInstance));
```

Let's not have Address.NO_OP_ADDRESS, let's make  ServiceEndpoint  to have null as service address.

**Review by dmytro-lazebnyi — APPROVED** [review]

**Review by artem-v — APPROVED** [review]

**Pull request merged**
