### PR TITLE
Release

### PR DESCRIPTION
**Pull request by aharonha**

### CODE REVIEW

**Comment by segabriel** [comment]
Let's create `scalecube-cluster` release, then update it here and make this release.

**Comment by aharonha** [comment]
> Let's create `scalecube-cluster` release, then update it here and make this release.

[here](https://github.com/scalecube/scalecube-cluster/pull/105)

**Comment by aharonha** [comment]
should be done after merging of #463

**Comment by aharonha** [comment]
there are still some problematic version declarations here

**Review by artem-v — APPROVED** [review]

**Pull request merged**
